### ISSUE TITLE
[question] Is chaining all the Rust versions really required?

### ISSUE THREAD

**Issue by apteryks** [dtolnay/bootstrap#3]
Hello!

Thanks for this work; it's a useful reference in trying to implement the mrustc-based Rust bootstrap on different systems.

The question I have is the one in the title; it seems wasteful to have to build N releases of Rust to bootstrap version N; do you know if there was an issue when attempting to reuse older versions to build the later ones?

Thanks!

**Comment by bjorn3** [comment]
No, it is not required. Building rustc normally uses the official build of the previous version of rustc. This is just to be able to verify that no malicious entity was able to change the official builds to perform a [trusting trust](https://users.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf) attack.

**Comment by apteryks** [comment]
OK, I see!  It's for comparison purpose with upstream.  So does it mean I can use a built mrustc (with the rustc 1.29 sources for the stdlib) to directly bootstrap the latest and greatest Rust?

**Comment by dtolnay** [comment]
Mrustc only supports building rustc 1.19.0 and 1.29.0, not any other version.

**Comment by apteryks** [comment]
I understand that, but after 1.29.0 is built, can it be used to build some rust later than the next one? E.g., can we shorten the bootstrap path to the final, current rust version? I'll try, but if you happen to know, I'm interested :-).

**Comment by bjorn3** [comment]
> I understand that, but after 1.29.0 is built, can it be used to build some rust later than the next one?

No, rustc can only bootstrap from the previous version. Once a new beta branches all `#[cfg(bootstrap)]`/`#[cfg(not(bootstrap))]` necessary to bootstrap from the beta before are removed from libstd and over time in many cases new language features start to get used by rustc.

**Comment by apteryks** [comment]
Thanks for answering my question!

Closing :-)
