### ISSUE TITLE
Start at rustc 1.39

### ISSUE THREAD

**Issue by aDotInTheVoid** [dtolnay/bootstrap#4]
Apparently mrustc can [build rustc 1.39 now](https://github.com/thepowersgang/mrustc/blob/master/build-1.39.0.sh). 

Doing this would reduce the bootstrap lenght, although I'm not sure its worth the effort to implement this, as it would still take ~10 bootstrap steps, and anyone who is willing to do that would probably be fine with the current ~20

**Comment by palfrey** [comment]
[1.54 now](https://github.com/thepowersgang/mrustc/blob/v0.10/build-1.54.0.sh)
